name: bloc_clean_arcitecture
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  fluttertoast: ^9.0.0
  cached_network_image: ^3.4.1
  another_flushbar: ^1.12.32
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  build_runner: ^2.8.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
